#!/usr/bin/env php

<?php

$CMD = 'python3';

if ($argc < 2) {
    echo "Usage: php artisan <command>\n";
    echo "Available commands: start, test\n";
    exit(1);
}

$command = $argv[1];

switch ($command) {
    case 'start':
        $serverCommand = 'php -S localhost:3000 -t app';
        echo "Starting server on localhost:3000...\n";
        passthru($serverCommand);
        break;

    case 'test':
        $testCommand = "$CMD tests/test_login.py";
        echo $testCommand . "\n";
        echo "Running tests...\n";
        passthru($testCommand);
        break;

    default:
        echo "Unknown command: $command\n";
        echo "Available commands: start, test\n";
        exit(1);
}
